# 星相运维平台prometheus地址即prometheus-stellar,默认为 "http://stellar-prometheus.kxdigit-monitoring.svc.cluster.local:9090"
prometheus_url: "http://172.31.101.239:46627/"
# skynet托管平台prometheus地址，需填写ip+端口
prometheus-skynet: "172.31.101.239"
prometheus-k8s: "172.31.101.239"  # k8s的prometheus监控地址，容器化部署时无需填写， 默认为"http://prometheus-k8s.kubesphere-monitoring-system:9090"
# 星云大数据prometheus地址，需填写ip+端口
prometheus-ddp: "172.31.101.239"

# Harbor仓库配置
harbor:
  enabled: true
  url: "https://172.30.137.161"  # 默认复用k8s主节点IP地址
  username: "root"
  password: "Harbor12345"
  insecure: true  # 是否忽略证书验证

project_name: "星相运维平台巡检报告"


# 定时任务：每天9点半和17半执行

cron_schedule: "15 16,17 * * *"


# 报告清理

report_cleanup:
  enabled: true
  max_age: 7    # 保留最近7天的报告
  cron_schedule: "0 0 * * *"  # 如果为空，则执行执行上面定时任务，即生成报告时清理

metric_types:
  - type: "自定义指标项组"
    metrics:
      - name: "/iflytek/data分区磁盘使用率"
        description: "/iflytek/data分区磁盘使用率统计"
        query: "avg by(ident, path, device) (disk_used_percent{path=~'/iflytek/data'})"
        threshold: 80
        threshold_type: "greater"
        unit: "%"
        labels:
          ident: "节点名称"
          path: "挂载点"
          device: "磁盘"

      # Pod运行状态已移至代码中硬编码实现，此处配置已移除