name: build-go-binary

on:
  push:
    tags:
      - 'v*' # 当 v* 标签被推送时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin] # 需要打包的系统
        goarch: [amd64, arm64] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.22.3 # 改为1.22.3版本，与Dockerfile保持一致
          binary_name: "PromAI" # 可以指定二进制文件的名称
          extra_files: README.md config outputs reports templates # 需要包含的额外文件